version: '3.9'
services:
  client:
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/app/src
  server:
    build: ./server
    ports:
      - 4000:4000
    volumes:
      - ./server:/usr/app/src