name: pr-github-actions
on: [pull_request]
jobs:
  test-mind-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install --prefix ./client
      - run: npm run test:coverage --prefix ./client